// 'Christmas',
// 'Birthday',
// 'LaborDay',
// 'ValentinesDay',
// 'Easter',
// 'MemorialDay',
// 'CustomDay',
export const jsonData = [
  {
    id: 'gift_001',
    name: 'Festive Christmas Mug',
    description:
      'A ceramic mug with Christmas-themed prints, perfect for hot cocoa.',
    price: 12.99,
    image: 'https://example.com/images/christmas-mug.jpg',
    occasion: 'Christmas',
  },
  {
    id: 'gift_002',
    name: 'Birthday Surprise Box',
    description:
      'A box filled with chocolates, a mini cake, and a birthday card.',
    price: 29.99,
    image: 'https://example.com/images/birthday-box.jpg',
    occasion: 'Birthday',
  },
  {
    id: 'gift_003',
    name: 'Labor Day BBQ Set',
    description: 'A complete BBQ grilling toolset for Labor Day celebrations.',
    price: 45.0,
    image: 'https://example.com/images/laborday-bbq-set.jpg',
    occasion: 'LaborDay',
  },
  {
    id: 'gift_004',
    name: "Valentine's Rose Bear",
    description: 'A handcrafted bear made of artificial roses in a gift box.',
    price: 34.95,
    image: 'https://example.com/images/valentines-rose-bear.jpg',
    occasion: 'ValentinesDay',
  },
  {
    id: 'gift_005',
    name: 'Easter Egg Hunt Kit',
    description: 'A colorful kit with plastic eggs, candies, and bunny toys.',
    price: 19.99,
    image: 'https://example.com/images/easter-egg-kit.jpg',
    occasion: 'Easter',
  },
  {
    id: 'gift_006',
    name: 'Memorial Day Flag Set',
    description:
      'American flag set for honoring and decorating on Memorial Day.',
    price: 15.49,
    image: 'https://example.com/images/memorialday-flag.jpg',
    occasion: 'MemorialDay',
  },
  {
    id: 'gift_007',
    name: 'Custom Engraved Keychain',
    description: 'Personalized keychain with your message for any custom day.',
    price: 9.99,
    image: 'https://example.com/images/custom-keychain.jpg',
    occasion: 'CustomDay',
  },
];
