export const surveyQuestions = [
  {
    id: 1,
    type: 'multiple-choice',
    question: 'What are your favorite hobbies?',
    options: [
      '📚 Reading',
      '🎮 Gaming',
      '🧘‍♀️ Yoga & Meditation',
      '🎨 Arts & Crafts',
      '🎵 Music & Instruments',
      '🏋️ Fitness & Gym',
      '🌱 Gardening',
      '🚀 Tech & Gadgets',
      '🍳 Cooking & Baking',
      '🏕️ Outdoor Adventures',
    ],
  },
  {
    id: 2,
    type: 'multiple-choice',
    question: 'What best describes your lifestyle?',
    options: [
      '🌿 Minimalist',
      '🏙️ Urban/Trendy',
      '🌍 Eco-friendly',
      '💼 Workaholic/Busy Professional',
      '💆 Self-Care & Wellness Enthusiast',
    ],
  },
  {
    id: 3,
    type: 'multiple-choice',
    question: 'What type of gifts excite you the most?',
    options: [
      '🎁 Surprise/Unique Finds',
      '🌟 Luxury/High-End Brands',
      '📦 Practical & Everyday Essentials',
      '🤣 Funny/Quirky Gifts',
      '❤️ Sentimental & Personalized Items',
    ],
  },
  {
    id: 4,
    type: 'multiple-choice',
    question: 'What categories of gifts do you enjoy receiving?',
    options: [
      '🏠 Home & Decor',
      '💄 Beauty & Skincare',
      '🍵 Coffee & Tea',
      '🖥️ Tech & Gadgets',
      '👕 Fashion & Accessories',
      '🛀 Self-Care & Relaxation',
      '🎧 Music & Entertainment',
      '🎮 Gaming & Collectibles',
      '🌿 Plants & Gardening',
    ],
  },
  {
    id: 5,
    type: 'multiple-choice',
    question: 'What’s your personality type when it comes to gifts?',
    options: [
      '🎭 I love fun and quirky gifts',
      '🏆 I appreciate high-quality & premium items',
      '🎨 I prefer creative & artsy gifts',
      '🧩 I enjoy puzzle & brain-teasing gifts',
      '🏡 I love cozy and homey gifts',
    ],
  },
  {
    id: 6,
    type: 'multiple-choice',
    limit: 3,
    question: 'What colors do you love seeing in your gifts?',
    options: [
      '🔵 Blue',
      '🔴 Red',
      '🟣 Purple',
      '🟢 Green',
      '⚫ Black',
      '⚪ White',
      '🟡 Yellow',
      '🌈 Surprise me!',
    ],
  },
  {
    id: 7,
    type: 'multiple-choice',
    question: 'Which occasions do you want gifts for?',
    options: [
      '🎂 Birthday',
      '🎄 Christmas',
      '💖 Valentine’s Day',
      '🎉 Other (Custom Date)',
    ],
  },
  {
    id: 8,
    type: 'single-choice',
    question: 'Do you want multiple gifts per holiday if your budget allows?',
    options: [
      '✅ Yes, if I have enough balance',
      '❌ No, just one perfect gift per holiday',
    ],
  },
  {
    id: 9,
    type: 'single-choice',
    question:
      'Would you like to receive gifts randomly throughout the year as a surprise?',
    options: [
      '✅ Yes! Random gifts would be fun',
      '❌ No, just on my selected holidays',
    ],
  },
  {
    id: 10,
    type: 'text',
    question: 'Do you have any allergies or items you do not want to receive?',
    placeholder: 'e.g., No peanuts, no scented candles, no leather items',
  },
];
export const giftData = [
  {
    id: 'gift_001',
    name: 'Festive Christmas Mug',
    description:
      'A ceramic mug with Christmas-themed prints, perfect for hot cocoa.',
    price: 12.99,
    image: 'https://example.com/images/christmas-mug.jpg',
    occasion: 'Christmas',
  },
  {
    id: 'gift_002',
    name: 'Birthday Surprise Box',
    description:
      'A box filled with chocolates, a mini cake, and a birthday card.',
    price: 29.99,
    image: 'https://example.com/images/birthday-box.jpg',
    occasion: 'Birthday',
  },
  {
    id: 'gift_003',
    name: 'Labor Day BBQ Set',
    description: 'A complete BBQ grilling toolset for Labor Day celebrations.',
    price: 45.0,
    image: 'https://example.com/images/laborday-bbq-set.jpg',
    occasion: 'LaborDay',
  },
  {
    id: 'gift_004',
    name: "Valentine's Rose Bear",
    description: 'A handcrafted bear made of artificial roses in a gift box.',
    price: 34.95,
    image: 'https://example.com/images/valentines-rose-bear.jpg',
    occasion: 'ValentinesDay',
  },
  {
    id: 'gift_005',
    name: 'Easter Egg Hunt Kit',
    description: 'A colorful kit with plastic eggs, candies, and bunny toys.',
    price: 19.99,
    image: 'https://example.com/images/easter-egg-kit.jpg',
    occasion: 'Easter',
  },
  {
    id: 'gift_006',
    name: 'Memorial Day Flag Set',
    description:
      'American flag set for honoring and decorating on Memorial Day.',
    price: 15.49,
    image: 'https://example.com/images/memorialday-flag.jpg',
    occasion: 'MemorialDay',
  },
  {
    id: 'gift_007',
    name: 'Custom Engraved Keychain',
    description: 'Personalized keychain with your message for any custom day.',
    price: 9.99,
    image: 'https://example.com/images/custom-keychain.jpg',
    occasion: 'CustomDay',
  },
];
